### ISSUE TITLE
Encrypt password stored

### ISSUE THREAD

**Issue by nicolas-bonnel** [flux-s/once-upon-a-time#1]
User passwords are currentlystored in database but not encrypted. They should be hashed. Perhaps use something like SSHA ?

**Comment by albanm** [comment]
See this [article](https://crackstation.net/hashing-security.htm).

I will use node's [crypto.pbkdf2](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback) for the digest and [crypto.randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) for the salt.
